app:
  filesystem:
    allowed-dir: /Users/diegoleon/personal-docs

spring:
  application:
    name: mcp-filesystem-client
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
    mcp:
      client:
        stdio:
          connections:
            filesystem:
              command: 'npx'
              args:
                - '-y'
                - '@modelcontextprotocol/server-filesystem'
                - ${app.filesystem.allowed-dir}
        toolcallback:
          enabled: true

